// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIJZIA3jl0Rvgy0HjBAo0BchY16sqVRA0',
    appId: '1:385054728978:web:9098827a3f21a0059809cb',
    messagingSenderId: '385054728978',
    projectId: 'sidestacks-1114d',
    authDomain: 'sidestacks-1114d.firebaseapp.com',
    storageBucket: 'sidestacks-1114d.firebasestorage.app',
    measurementId: 'G-QWZTZY5WVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGdwW15MqPwtDw-fgmezlZe6tzx2PK9h8',
    appId: '1:385054728978:android:f65a989b453b56009809cb',
    messagingSenderId: '385054728978',
    projectId: 'sidestacks-1114d',
    storageBucket: 'sidestacks-1114d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANOMjngylDtuLhzHUUHsSwH0JMnEcOok4',
    appId: '1:385054728978:ios:a7a3eaa555052f9c9809cb',
    messagingSenderId: '385054728978',
    projectId: 'sidestacks-1114d',
    storageBucket: 'sidestacks-1114d.firebasestorage.app',
    iosClientId: '385054728978-923kek0l16uja7ov2lvfi52ha9d016id.apps.googleusercontent.com',
    iosBundleId: 'com.example.sidestack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANOMjngylDtuLhzHUUHsSwH0JMnEcOok4',
    appId: '1:385054728978:ios:a7a3eaa555052f9c9809cb',
    messagingSenderId: '385054728978',
    projectId: 'sidestacks-1114d',
    storageBucket: 'sidestacks-1114d.firebasestorage.app',
    iosClientId: '385054728978-923kek0l16uja7ov2lvfi52ha9d016id.apps.googleusercontent.com',
    iosBundleId: 'com.example.sidestack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIJZIA3jl0Rvgy0HjBAo0BchY16sqVRA0',
    appId: '1:385054728978:web:6a883ca9bbda2e449809cb',
    messagingSenderId: '385054728978',
    projectId: 'sidestacks-1114d',
    authDomain: 'sidestacks-1114d.firebaseapp.com',
    storageBucket: 'sidestacks-1114d.firebasestorage.app',
    measurementId: 'G-ZE8M0HDGYC',
  );
}
